### ISSUE TITLE
Differences from Test::MockTime?

### ISSUE THREAD

**Issue by karenetheridge** [powerman/perl-Test-Mock-Time#1]
There are two time mockers -- what is the difference between them?  Why would I want to choose this one over the other one?  It would be great if this could be explained in a "SEE ALSO" section of the documentation.

**Comment by powerman** [comment]
Hmm… More docs is always a good thing, but I believe this question is clearly answered in module description:
- Test::MockTime handles only CORE::GLOBAL::\* time
- Test::MockTime::HiRes handles only Time::HiRes::\* time
- Test::Mock::Time handles everything above plus event loop related modules - actually it's only CPAN module at this time which support mocking time for event loops and enable testing things like:

``` perl
use Test::More tests=>1;
use Test::Mock::Time;
use EV;
my $t = EV::time;
my $w = EV::timer 3600, 0, sub { EV::break };
EV::run;
is EV::time, $t+3600, 'timer elapsed in 1 hour';
```

And this test will complete immediately, without waiting for hour:

```
$ time perl test.pl 
1..1
ok 1 - timer elapsed in 1 hour

real 0m0.107s
user 0m0.083s
sys  0m0.006s
```

**Comment by eserte** [comment]
> There are two time mockers

There are even more, for example https://metacpan.org/pod/Time::Fake

**Comment by nicomen** [comment]
https://metacpan.org/pod/Time::Mock too?

**Comment by nicomen** [comment]
Actually, this module has an ok SEE ALSO part, you might want to include something like that: https://metacpan.org/pod/Test::MockDateTime

**Comment by nrdvana** [comment]
(I think you can close this issue.  The docs were immediately clear to me that I had found a module that would mock more things than Test::MockTime)
