### ISSUE TITLE
Subroutine redefined at lib/Test/Mock/Time.pm line 413.

### ISSUE THREAD

**Issue by fschlich** [powerman/perl-Test-Mock-Time#10]
Hi,

running a syntax check on Test::Mock::Time, as is routinely done by Debian's autopktest for example, produces two warnings with version 0.2.0 (and Perl 5.36, EV 4.34):

```
$ perl -wc lib/Test/Mock/Time.pm
Subroutine Test::Mock::Time::inf redefined at lib/Test/Mock/Time.pm line 413.
Subroutine Test::Mock::Time::NaN redefined at lib/Test/Mock/Time.pm line 413.
lib/Test/Mock/Time.pm syntax OK
```

I think this is caused by first calling `use bignum` in line 305 and then `use bigint` in line 413, the latter of which used to be "use bignum" as well before 0.2.0. Changing that back to `use bignum` fixes things for me, while the tests still pass, so perhaps [that change](https://github.com/powerman/perl-Test-Mock-Time/commit/3ecb90c8106485dd4bea2751a228dc25fa4a585e#diff-61761f83ded75fd17c2298826b121ca079487da2cc0419adbac527452cca5b14L411) was unintended?

**Comment by powerman** [comment]
I think you right. Fixed in 0.2.1. Thanks!
