### ISSUE TITLE
Time::HiRes.t - invalid name on Windows

### ISSUE THREAD

**Issue by chorny** [powerman/perl-Test-Mock-Time#5]
Windows does not allow ':' in file names.

**Comment by powerman** [comment]
Yeah, thanks, already noticed and fixed this by https://github.com/powerman/perl-Test-Mock-Time/commit/71246ef72455638038605efc8e126a7aaa5eb30e - just didn't released on CPAN yet, I'd like to get more reports from CPAN Testers and fix more issues at once.
