### ISSUE TITLE
[Feature Request] An option to specify starting value for time()

### ISSUE THREAD

**Issue by kappa** [powerman/perl-Test-Mock-Time#7]
Sometimes it is not enough to control the relative movement of time in tests. To be able to test code that depends on absolute value of time and its passage starting from that point on it would be great to have Test::Mock::Time start counting from a specified moment.

Test::MockTime & Test::Time do that but they do not mock event loop timers and are not compatible with Test::Mock::Time.

**Comment by powerman** [comment]
At a glance it doesn't sounds like a good idea to freely move time forward and backward for application with event loop and timers. Probably you should try to implement what you want in different ways, for example:
- re-base your absolute time values hardcoded in code/test on value returned by time() when test starts
- if you need to test some fixed point in the future then on test start check difference between time() and that future point of time and then do ff($difference) - this way you'll set test starting time at that point of time

**Comment by kappa** [comment]
I agree that moving time backwards is not a very practical feature, but testing the code that is intended to run at specific moments in the future is important and often neglected. Long-running apps with timers set hours or even days away from the present are not that rare.

Thank you, I like your second approach more than the direct one I implemented for myself (just set $Absolute to a value at the very beginning, before starting the loops).
